version: "2"

services:

  clouddriver:
    env_file: ./compose.env
    image: stephlag/spinnaker-clouddriver:latest
    volumes:
      - /opt/clouddriver/credentials:/opt/clouddriver/credentials
    ports:
      - "7002:7002"
  deck:
    environment:
      - API_HOST=http://localhost:8084
      - DECK_HOST=0.0.0.0
    image: stephlag/spinnaker-deck:latest
    ports:
      - "9000:9000"

  echo:
    env_file: ./compose.env
    # environment:
    #   - "JAVA_OPTS=-javaagent:/opt/echo/lib/jamm-0.2.5.jar"
    image: stephlag/spinnaker-echo:latest

  front50:
    env_file: ./compose.env
    # environment:
      # - "JAVA_OPTS=-javaagent:/opt/front50/lib/jamm-0.2.5.jar"
    image: stephlag/spinnaker-front50:latest

  gate:
    env_file: ./compose.env
    image: stephlag/spinnaker-gate:latest
    ports:
      - "8084:8084"

  igor:
    env_file: ./compose.env
    image: stephlag/spinnaker-igor:latest
    ports:
      - "8088:8088"

  orca:
    env_file: ./compose.env
    image: stephlag/spinnaker-orca:latest

  redis:
    command: "redis-server --appendonly yes"
    image: redis:3.2-alpine

  jenkins:
     image: jenkins:alpine
     ports:
       - "9090:8080"
       - "50000:50000"

  # rosco:
  #   env_file: ./compose.env
  #   image: stephlag/spinnaker-rosco:latest

  # fiat:
  #   env_file: ./compose.env
  #   environment:
  #     - SERVICES_CLOUDDRIVER_HOST=clouddriver
  #     - SERVICES_FRONT50_HOST=front50
  #   image: spinnaker-fiat:latest
